version: 2
updates:
  # Check for Python dependency updates
  - package-ecosystem: "pip"
    directory: "/"  # Root directory of the repository
    schedule:
      interval: "weekly"  # Frequency of checks (daily, weekly, monthly)