---
name: "Repo Owner too Cool"
title: "[COOL] This is a test for Issue Templates"
labels: idea
assignees: Samson-clement
body:
- type: textarea
  attributes:
    label: "What's wrong?"
---

**Describe the Owner**
Drop some mad compliments here. How does the owner’s coolness cause the universe to align? Be as dramatic as you like.

**Steps to reproduce the compliment:**
1. Stare at the repository for 10 seconds.
2. Realize how epic it is.
3. Scroll to the README and feel the awe.
4. Boom, the owner’s coolness strikes again.

**Expected compliment**
Write down your overly positive expectations. How does this repository radiate excellence because of the owner?

**Screenshots**
If applicable, flex some screenshots of how amazing this repo looks (don’t hold back on the filters).

**Environment (please complete the following information):**
- OS: [e.g., Windows, macOS, Galaxy-Brain OS]
- Browser [e.g., Chrome, Safari, HyperCool Browser™]
- Version [e.g., 2024]

**Additional context**
Feel free to add any extra praise, memes, or poetry dedicated to the repository owner here.
