---
name: Repo Owner too Cool
about: Compliment the owner for being too lit
title: "[COOL] This is a test for Issue Templates"
labels: idea
assignees: Samson-clement
---

**Describe the Owner**
A clear and concise description of your thoughts about the owner that are causing the issue...

**Steps to reproduce the compliment:**
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

**Expected compliment**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
- OS: [e.g., Windows, macOS]
- Browser [e.g., Chrome, Safari]
- Version [e.g., 22]

**Additional context**
Add any other context about the problem here.
